### PR TITLE
Check if current version is the latest version

### LINKED ISSUE #152: Detect when client is out of date
At the moment it is unclear if the user is running an outdated client. It would be good to add a warning on startup if the client is out of date, and an error if an old version is explicitly unsupported. We would probably need a new endpoint on Grand Challenge to do this.

### PR DESCRIPTION
**Pull request by HarmvZ**
Closes #152 

Checks the version and produces a warning on import when a newer version is available on pypi.

### CODE REVIEW

**Review by jmsmkn — APPROVED** [review]
I was wondering if we should have an API endpoint for this in addition to this? That way we can block versions that are no longer supported and force an upgrade.

**Comment by HarmvZ** [comment]
That's a good idea. So an endpoint on gc that returns the lowest supported version which will make gcapi raise an error if it's version is lower?

**Comment by jmsmkn** [comment]
Indeed!

**Comment by chrisvanrun** [comment]
Eh, something went wrong with drinking my coffee AND my local main wasn't clean =/

**Comment by chrisvanrun** [comment]
Going to close this in favour of an easy cherry-picked re-do.

**Pull request closed without merging**
